export default[
//     { "label": "Listing Title", "name": "listingTitle", "icon": "FaClipboardList" },
//   { "label": "TagLine", "name": "tagline", "icon": "FaTag" },
//   { "label": "Original Price", "name": "originalPrice", "icon": "FaDollarSign" },
//   { "label": "Selling Price", "name": "sellingPrice", "icon": "FaMoneyBillAlt" },
  { "label": "Category", "name": "category", "icon": "FaCar" },
  { "label": "Condition", "name": "condition", "icon": "FaCheckCircle" },
  { "label": "Type", "name": "type", "icon": "FaClipboardCheck" },
  { "label": "Make", "name": "make", "icon": "FaCar" },
  { "label": "Model", "name": "model", "icon": "FaCarSide" },
  { "label": "Year", "name": "year", "icon": "FaCalendarAlt" },
  { "label": "Drive Type", "name": "driveType", "icon": "FaRoad" },
  { "label": "Transmission", "name": "transmission", "icon": "FaExchangeAlt" },
  { "label": "Fuel Type", "name": "fuelType", "icon": "FaGasPump" },
  { "label": "Mileage", "name": "mileage", "icon": "FaTachometerAlt" },
  { "label": "Distance Travelled", "name": "distanceTravelled", "icon": "GiPathDistance" },
  { "label": "Engine Size", "name": "engineSize", "icon": "FaWrench" },
  { "label": "Cylinder", "name": "cylinder", "icon": "FaCogs" },
  { "label": "Color", "name": "color", "icon": "FaPalette" },
  { "label": "Door", "name": "door", "icon": "FaDoorOpen" },
//   { "label": "VIN", "name": "vin", "icon": "FaIdCard" },
//   { "label": "Offer Type", "name": "offerType", "icon": "FaHandHoldingUsd" },
//   { "label": "Listing Description", "name": "description", "icon": "FaFileAlt" }
]